### ISSUE TITLE
feedback for time selector

### ISSUE THREAD

**Issue by tbba** [stefangabos/Zebra_Datepicker#101]
Since this is in beta, I would like to give a quick feedback on the time selector.
(testing with bootstrap interface)

I got some feedback from users:
It is not immediately obvious that the modal is about setting a time because the elements have such large gaps and look like 9 separate elements. The "down" arrows are even closer to the bottom menu so it appears that those group together, what is misinterpretation.
If I would build this, I would add a ":" between the numbers, so it it more obvious this is a time.
And I would reduce all gaps so that the tike numbers and it's arrows are a little bit closer together (centered on the modal screen)
If the bottom menu had a slightly different grey, and maybe you can see the buttons, it would be more obvious that this is a menu and not part of the form.

Changing minutes can mean up to 59 taps.
As an alternative, what about an hour- and minute.- slider? - example:
http://trentrichardson.com/examples/timepicker/

What do you think?

**Comment by stefangabos** [comment]
Thank you for the feedback!
- i agree that visually it could do better: adding ":" between the numbers will make it more obvious that this is about time; i'll play a bit with the interface and see what I can come up with but I am unable to give you a time-frame - I work on these mostly on weekends
- allowing user input would allow for faster input;
- a slider is out of the question at this point as it requires quite some code to make it look and feel nice

**Comment by stefangabos** [comment]
I've rewrote the entire CSS and I think the time picker looks better now - let me know what you think,
Regarding the fact that users may have to click 59 times on minutes, maybe setting the `enabled_hours`, `enabled_minutes` and `enabled_seconds` properties would help

**Comment by tbba** [comment]
very nice!  Looks exactly like a "time" field now and it works perfectly. I was able to hide seconds, and set minutes to "every 10 minutes" (with the array), sparing the users a lot of clicks.

**Comment by stefangabos** [comment]
Thanks for the positive feedback! Can we close this now?
