### ISSUE TITLE
6 rows of days

### ISSUE THREAD

**Issue by rolandbalogh** [stefangabos/Zebra_Datepicker#103]
It would be nice if I had an option to set true or false for this:

A lot of times a month view has a full week with days which aren't in that month. I'd like to hide that row. Thanks, and sorry for my english.

![group](https://user-images.githubusercontent.com/868498/33662399-ec7371de-da8b-11e7-9ebc-9251abd1e492.png)

**Comment by stefangabos** [comment]
I don't like that the date picker's height would constantly change as we move from month to month...
