### ISSUE TITLE
Using update() to change custom_classes not working?

### ISSUE THREAD

**Issue by jafin** [stefangabos/Zebra_Datepicker#104]
Attempting to use update() to refresh which dates a custom class should be applied. Using something similar to:
```
calendar().update({custom_classes: {'bookingCalendar--week1': ['5 12 2017']}});
```
The prop is being set in the custom settings, but the UI does not reflect the change.

**Comment by stefangabos** [comment]
I can't confirm this.
Open the [examples](https://stefangabos.github.io/Zebra_Datepicker/), open the console and paste this in the console
```javascript
$('#datepicker').data('Zebra_DatePicker').update({custom_classes: {'test': ['30 12 2017']}});
```
Now open the first example and inspect day 30 of December 2017. You will see the class `test` was added

**Comment by jafin** [comment]
Thanks, using your example:

If the date picker is open and you run 
`$('#datepicker').data('Zebra_DatePicker').update({custom_classes: {'test': ['30 12 2017']}});`
It does not appear to add the class until it is reopened.

If you then run a second time  (picker is either shut or open)
`$('#datepicker').data('Zebra_DatePicker').update({custom_classes: {'test2': ['30 12 2017']}});`
then it does not appear to update the class to 'test2', and still shows 'test' as the class.

**Comment by stefangabos** [comment]
Could not reproduce the first issue. As long as you set the precedence correctly for your CSS (i.e. `.Zebra_DatePicker .dp_body td.test`) the CSS properties are being applied.

Also, I fixed second issue, the one where subsequent custom classes were not being applied after one custom class was already applied. Thank you!
