### ISSUE TITLE
Support multiple custom classes per date

### ISSUE THREAD

**Issue by jafin** [stefangabos/Zebra_Datepicker#105]
It would be great to have the option to apply multiple custom classes to dates. 

Example scenario, multiple built up styles

```
.class1 {background-color:'red'}
.calss2 {font-weight:bold}
```

**Comment by stefangabos** [comment]
This should already work if you're setting them like

$('#datepicker').data('Zebra_DatePicker').update({custom_classes: {'class1 class2 class3': ['30 12 2017']}});
