### ISSUE TITLE
remove attribute readonly="readonly" from input

### ISSUE THREAD

**Issue by aniculita** [stefangabos/Zebra_Datepicker#109]
Hi

I have the zebra datepicker inside a collapsible bootstrap area which is set to be collapsed initially (so datepicker is not visible). 
But when I expand the collapsible area, the input of datepicker gets an readonly attribute who does not allow me to enter manually the date.
I want to be able to insert manually the date, after expanding collapsible area and the datepicker gets visible :)

<input name="" class="datepicker form-control" type="text" **readonly="readonly"** placeholder="dd/mm/yyyy" value="" data-zdp_format="d/m/Y">

Any ideas? thank you !!

**Comment by stefangabos** [comment]
Set `readonly_element` option to FALSE

**Comment by aniculita** [comment]
Yes, it is set to false but is no working

/*
 * Display date picker where needed
 */
function HRdisplayDatePicker() {
  if ($.isFunction($.fn.Zebra_DatePicker)) {
    $('.datepicker').Zebra_DatePicker({
      readonly_element: false,
      select_other_months: true,
      open_icon_only: true,
      format: "d/m/Y"
    });
  }
}

**Comment by stefangabos** [comment]
hmmm, ok, will look into it. thanks!

**Comment by aniculita** [comment]
Thank you !!!!!

**Comment by stefangabos** [comment]
is there any callback that you run when showing the collapsible?

**Comment by aniculita** [comment]
yes
