### ISSUE TITLE
Common options for multiple datepickers

### ISSUE THREAD

**Issue by yark** [stefangabos/Zebra_Datepicker#110]
It would be nice if it will be possible to setup default options for all datepickers at page and then customize only some of them.

I have three datepickers on my page with cusom months and days names and i need to include it in all three .Zebra_DatePicker() calls or go throug ugly constructions as

```
common_options = {a: 1, b: 2};
date1_options = Object.assign({}, common_options, {c: 10});
date2_options = Object.assign({}, common_options, {c: 20});
date3_options = Object.assign({}, common_options, {c: 30});
```

**Comment by stefangabos** [comment]
I can't think of a better way than what you did there. It's how I would do it myself. I am open to suggestions though

**Comment by yark** [comment]
@stefangabos Zebra_Datepickerhame some default options now.

    {direction: 0, default_position: "above"}

It's possible to create method to set that options globally for all future initialized datepickers.
E.g.

    Zebra_Datepicker.defaults({direction: false, default_position: "below"});

and than 

    $('input.datepicker').Zebra_DatePicker();

will be initialized with custom set of default values ({direction: false, default_position: "below"})
or

    $('input.datepicker').Zebra_DatePicker({direction: -10});

will be initialized with overriden value of direction: -10, and still cusom default value of default_position "below" but not the initial default "above"

Pretty simple solution as for me.
