### ISSUE TITLE
Internationalization?

### ISSUE THREAD

**Issue by marcelgeratsch** [stefangabos/Zebra_Datepicker#111]
Why is it not possible to change the language? Cant find anything on the examples or the whole web. Just a ruby gem, which i cannot use. You really develop a datepicker without the possibility to set the language?

**Comment by stefangabos** [comment]
Have you looked in the documentation?

**Comment by marcelgeratsch** [comment]
Seriously i cant find it. Sorry. please give me a hint

**Comment by stefangabos** [comment]
Look for the `days`, `days_abbr`, `months` and `months_abbr` options...

**Comment by stefangabos** [comment]
There's no file. You just add your language in the configuration file
