### ISSUE TITLE
12h time format changes selected date (and sometimes time)

### ISSUE THREAD

**Issue by AnthonyHache** [stefangabos/Zebra_Datepicker#112]
Hi, when using a format that involves 12h time (rather than 24h), changing the time using the time picker can cause the selected date to increment.

Steps to reproduce:

- Setup a basic date picker with the following format : 'Y-m-d g:i A'
- Open the date picker, select a date
- Adjust the time picker to "11:xx pm"
- Use arrows to increment the hour to 12 (this will cause the selected date to increment by 1, it will set the select time to 12:xx am, but the time picker that is still open will still display "PM")
- Toggle from PM to AM (this will cause the selected time shown in the date picker to update to 12:xx pm )
- With PM selected in the time picker, change form 12:xx PM to 1:xx pm, and then change back to 12:xx PM (this will also cause the date to increment by one)
- When the select hour is 12, the time picker and the actual selected date/time in picker will always show opposite values for am / pm

A possibly 'separate' but highly related issue:
- Set the date/time picker to any date and set the time to "12:xx pm"
- Re-open the date/time picker and click on the "time picker" icon at the bottom right of the modal. (The "pre-selected" time will be the "current time", not "12:xx pm" which was previously set.

**Comment by AnthonyHache** [comment]
I've parsed through the source code and identified where the issue lies. When create a new Date object, there is some logic that "adds 12 hours" to the selected hours when using a 12h format, however it is not correct.
The selectable hours in a 12h format are 1 through 12. In the case of 12am (i.e. hour 0), we don't want to add 12hours to that value since then we end up passing in an hour value of 24 into the date constructor, and the constructor seems to handle that doing a "%24" op on the hour and taking any carry over and adding days to the resulting date object.
In the `select_date` function, we should be adjusting the hour value as follows: 
`var adjusted_hour = (timepicker_config && timepicker_config.hours ? selected_hour + (timepicker_config.ampm ? (selected_ampm === 'pm' && selected_hour !== 12 ? 12 : (selected_ampm === 'am' && selected_hour === 12 ? -12 : 0)) : 0) : 12);`

Likewise, in the `check_date` function, we should be adjusting the hour as follows: 
`var adjusted_original_hour = original_hours + (original_ampm === 'pm' && original_hours !== 12 ? 12 : (original_ampm === 'am' && original_hours === 12 ? -12 : 0));`

These could likely be handle in a new function so that the behaviour is consistent and easy to maintain. I will create a Pull Request shortly with a suggested change.

**Comment by michealharrington** [comment]
This is still an issue. I tested it locally and it still increments the day when toggling between 12 and 1 and going between 12 pm and 12 am. The code @AnthonyHache uses does fix the problem.

**Comment by AnthonyHache** [comment]
@stefangabos The solution I provided would have fixed the issue. This is still an issue in the "latest commit" you provided. Since you closed the issue I am no longer able to "Re-Open" it. Will you re-open it or should I create a new issue?
Thanks.

**Comment by stefangabos** [comment]
With you code, if you set to AM and keep going with the `hour` the date will change everything you pass over `12` (the date will increase if you are going upwards or will decrease if you are going downwards).

Is this the expected behaviour?

**Comment by stefangabos** [comment]
On an unrelated note I also noticed that the AM/PM is too close to the `:` on its left :)

**Comment by stefangabos** [comment]
I'm sorry I was not testing correctly - it seems that your code works correctly after all...
