### ISSUE TITLE
Incorrect icon position when used on modal dialog

### ISSUE THREAD

**Issue by galcott** [stefangabos/Zebra_Datepicker#114]
I am using the plugin in a form on a jQueryUI modal dialog, and the icon does not position correctly, as shown in this screen shot. The "inside" option is set to the default of true (if I set that to false then the icon shows up all the way on the left of the input!) . When I use it outside the modal it displays correctly. Is there a way to fix this?
![zebra](https://user-images.githubusercontent.com/4509764/38175219-e84e1aa2-35a6-11e8-8a10-a6889b909b59.jpg)

**Comment by stefangabos** [comment]
can you please provide a jsfiddle or some HTML markup so I can reproduce this?

**Comment by stefangabos** [comment]
this happens because the input elements are not visible initially; you should call the `update` method in the modal dialog's [open](http://api.jqueryui.com/dialog/#event-open) event
