### ISSUE TITLE
Multiple time pickers affect each other

### ISSUE THREAD

**Issue by michealharrington** [stefangabos/Zebra_Datepicker#115]
When there are multiple time pickers on the page, selecting a time on one will select the time on all other time pickers that are empty.

If I have 2 time pickers on screen and I select a time on time picker A and then clear it. Selecting a time on time picker B will give time picker A the same time, but with a date of 1900-01-01.

I fixed the problem locally by add context to the date picker's jquery selectors at lines lines **1553** and **1554**

```javascript
// as users may click this before making any adjustments to time, simulate time adjustment so that
// a value is selected
$('.dp_time_controls_increase td', timepicker).trigger('click');
$('.dp_time_controls_decrease td', timepicker).trigger('click');
```

**Comment by stefangabos** [comment]
Thank you!
