### ISSUE TITLE
Incorrect Icon position on Chrome at 110% magnification

### ISSUE THREAD

**Issue by cormacmcs** [stefangabos/Zebra_Datepicker#117]
Icon position low in input when window magnification is set to 110% on chrome. Does not happen at 100% or 120% only 110%. This can be seen even on the examples page. 
![zebra_datepicker_mag_bug](https://user-images.githubusercontent.com/8311479/39046829-72e5e9e6-448f-11e8-8605-5a70efa5b57d.png)

**Comment by stefangabos** [comment]
This was an issue with jQuery that was fixed in 3.3.1
Thank you!
