### ISSUE TITLE
Question on disabled days within a month view

### ISSUE THREAD

**Issue by sempbevan** [stefangabos/Zebra_Datepicker#119]
Good morning.

Is there a reason the prev-month and next-month days within a month view are disabled?  Is there a way to make them clickable?
![capture](https://user-images.githubusercontent.com/8549270/41917569-55dbb3e2-7920-11e8-9c30-24dbe8694211.PNG)

Thank you for your time.

**Comment by stefangabos** [comment]
The reason is that that's how I like it :)
See the `select_other_months` option for enabling them

**Comment by sempbevan** [comment]
The best reason of all!  Great tool.  Thank you.
