### ISSUE TITLE
Problem setting start_date with scandinavian charecters like äö and å

### ISSUE THREAD

**Issue by uusikyla** [stefangabos/Zebra_Datepicker#120]
Hi!

I'm trying to set an start_date for two paired Zebra_DatePicker Input boxes generated from my database in my webbased system.

It works when I use the format: 'Y-m-d' but I need to get it to work with the format: 'l d.m.Y H:i'?
In the documentation it says that the system will ignore start_date if you don't enter the date in the right format.

So I'm using scandinavian character in my date format like:
format: 'l d.m.Y H:i',
start_date: 'Söndag 02.07.2018 14:00',

How can I get this to work?

**Comment by uusikyla** [comment]
I'm sorry but I'm new to GitHub so where can I download the latest "commit"? :)

**Comment by stefangabos** [comment]
By clicking on the green "Clone or download button" you get the "latest commit" (the most up-to-date code but necessarily the "stable" code - think of it as "work in progress"). You would get the latest stable release by going to the "Releases" tab and downloading the latest version from there

**Comment by stefangabos** [comment]
is this working for you?
