### ISSUE TITLE
set_date using optional new Date() instance

### ISSUE THREAD

**Issue by alexanderKikhaev** [stefangabos/Zebra_Datepicker#122]
for example, tomorrow date:

var d = new Date(); d.setDate(d.getDate() + 1);
$('#dt_from').data('Zebra_DatePicker').set_date( d );

to get it now I need convert it to specified format, but this function already has inside the library. so 

To support this future need one line inside
plugin.set_date = function(date):

var dateObj;
if (typeof(date)==='object') date = format(date);
....

this future is very helpful after any js date change, especially when new dynamic forms are creating

**Comment by stefangabos** [comment]
Done. Thank you!
