### ISSUE TITLE
src/* removed due to .npmignore

### ISSUE THREAD

**Issue by edwinveldhuizen** [stefangabos/Zebra_Datepicker#123]
I was trying to write some custom style by fetching the `template.scss` and using my own variables values.
Sadly, the file is not included due to the `.npmignore` rules, any chance it can be included? 😊

**Comment by stefangabos** [comment]
That is the intended behaviour as 99.99% of people don't need other files except those that make the date picker work. The only way to get *all* the files is to clone the repository

**Comment by edwinveldhuizen** [comment]
but for the people who do you could consider not hiding it, right?
Or by including the template.scss in the dist folder

**Comment by edwinveldhuizen** [comment]
Cloning entire repos doesn't really fit in a neat npm dependency/building flow 😉

**Comment by stefangabos** [comment]
no , it will remain as it is now - sorry to disappoint you :) i need a better argument for adding the build files to the distribution and not keeping it clean.

if you want to do your own templates you'll have to clone the repository, do `npm install` and then run `grunt`. you'll have to have a look in `Gruntfile.js` and add/adjust the paths to your template wherever is required.
