### ISSUE TITLE
onClose event firing on document resize

### ISSUE THREAD

**Issue by kouts** [stefangabos/Zebra_Datepicker#124]
onClose event for some reason fires on window resize after the datepicker is closed.
Check this fiddle here [https://jsfiddle.net/xpvt214o/727583/](https://jsfiddle.net/xpvt214o/727583/)

Open the datepicker, then close it and watch onClose event firing while you resize the window.
![onclose](https://user-images.githubusercontent.com/2233663/44994374-ff73a100-afa6-11e8-934f-a4e2bb8f4908.gif)

**Comment by stefangabos** [comment]
should be fixed now. thank you!
