### ISSUE TITLE
Is there an option to make the calendar Right-to-Left? to support rtl languages

### ISSUE THREAD

**Issue by Abdox3** [stefangabos/Zebra_Datepicker#126]

**Comment by stefangabos** [comment]
Sorry, my experience with rtl languages is close to none so I don't even know where to start. Can you please give me a date picker as an example? Thanks!

**Comment by Abdox3** [comment]
like this one:
https://demos.telerik.com/kendo-ui/datetimepicker/right-to-left-support

**Comment by stefangabos** [comment]
I don't see anything different on the date picker itself. The rtl on the element the date picker is attached to is up to you to style. The format of that date is "a H:i d/m/Y"

**Comment by stefangabos** [comment]
And setting "icon_position" to "left"

**Comment by Abdox3** [comment]
Thanks for fast responding 👍 

The differences are: day's names start from right to left, this sequence: sa fr th we tu mo su, as well as the day's numbers start from right to left.
also the months goes as:
4 3 2 1
8 7 6 5
12 11 10 9.
Years sequence: 
2013 2012 2011
2016 2015 2014
2019 2018 2017
The years and months, if you click the right arrow it goes to the previous year/month, the left arrows goes to the next year/month.

**Comment by Abdox3** [comment]
Thanks I really appreciate that. And sure take your time.

**Comment by stefangabos** [comment]
let's keep this open so you get notified when it's done. thanks!

**Comment by Abdox3** [comment]
Ok, sorry I just thought that it would comment and close the tap x.x, it is just the first time I start an issue.
Thanks again.

**Comment by stefangabos** [comment]
you now have RTL support in the latest commit. would you be so kind to test it a little bit and let me know if it works as expected? thank you!

**Comment by Abdox3** [comment]
Thank you very much, I have tested it, it works great!! <3

![2018-10-27_115026](https://user-images.githubusercontent.com/33580591/47601828-a5a7ba00-d9de-11e8-8b5a-17bd12a663e0.jpg)

**Comment by stefangabos** [comment]
I am glad I could help - thank you for bringing this up and for testing it!
