### ISSUE TITLE
Proposition: Add option that makes days of next/previos month selectable

### ISSUE THREAD

**Issue by mckey** [stefangabos/Zebra_Datepicker#128]
![image](https://user-images.githubusercontent.com/1488339/47204455-035b5700-d38c-11e8-90e4-3dd8d8a14859.png)

**Comment by stefangabos** [comment]
Set `select_other_months` to `TRUE`

**Comment by mckey** [comment]
Thank you!

**Comment by stefangabos** [comment]
no problem
