### ISSUE TITLE
Date formats using ICU standards

### ISSUE THREAD

**Issue by Yamakasi** [stefangabos/Zebra_Datepicker#131]
Hi,

Are you able to add the ICU standards for the dateformat ? The issue is that when you come from other languages that uses them they don't lineup.

This would be great!

Thanks

**Comment by stefangabos** [comment]
Please tell me what is not working. What have you tried, what did you expect, and what did actually happen. Thanks!

**Comment by Yamakasi** [comment]
You are using the formats from date() which are not locale based like intlDateFormatter does:

**Comment by stefangabos** [comment]
i'm definitely not going to change how the formats are set :) but I was wondering what is the reason for asking this, as maybe there already is a solution: what is it that you are unable to achieve?

**Comment by Yamakasi** [comment]
date() formats are not locale standards... that is why I would suggest ICU. So what I like to achive ? proper locale formatting.

**Comment by stefangabos** [comment]
you can already use day and month names in your language

**Comment by Yamakasi** [comment]
Yes but if you format using intlDateFormatter formats... it's not ideal.

**Comment by stefangabos** [comment]
sorry, this is all I have :)

**Comment by Yamakasi** [comment]
Optimize it :) more languages have this. It's standard at the end... so you will have the best datetimepicker when you do... I just checked them all for it!

**Comment by stefangabos** [comment]
you'll have to use another datepicker because I am not going to invest time in this...

**Comment by Yamakasi** [comment]
Pity, you should use standards.
