### ISSUE TITLE
data-zdp_pair returning jQuery TypeError

### ISSUE THREAD

**Issue by LDemouge** [stefangabos/Zebra_Datepicker#133]
hello Stefan,

thx for this plugin i've been using for years!

today i'm trying to use the `pair ` option as a data attribute like this
`<input data-zdp_pair="#theElemToPairWith">` 

or like this 
`<input data-zdp_pair="jQuery('#theElemToPairWith')">` 

but it's returning the following error 

> TypeError: right-hand side of 'in' should be an object, got string
M                             **/js/jquery-1.10.2.min.js:4:7769
each                        **/js/jquery-1.10.2.min.js:4:5202
update_dependent **/js/datepicker/zebra_datepicker.src.js:2827:17
init                           **/js/datepicker/zebra_datepicker.src.js:852:26
$.Zebra_DatePicker  **/js/datepicker/zebra_datepicker.src.js:2958:9
$.fn.Zebra_DatePicker **/js/datepicker/zebra_datepicker.src.js:2974:26
each                         **/js/jquery-1.10.2.min.js:4:5345
each                         **/js/jquery-1.10.2.min.js:4:1997
$.fn.Zebra_DatePicker **/js/datepicker/zebra_datepicker.src.js:2965:16

I  updated jQuery and i got a slightly more expressive error message 

> TypeError: cannot use 'in' operator to search for 'length' in 'jQuery('#end_NWJ...'

do you think you can help me there?

**Comment by stefangabos** [comment]
Does it work when setting the `pair` option from JavaScript?

**Comment by stefangabos** [comment]
I don't think it will work when specifying as a data attribute as, if I remember correctly, the `pair` attribute expects a jQuery object and I don't think you even have jQuery available when the browser is going over the HTML - unless you include jQuery in the `<head>` (which I hope you don't). But, if you'd had jQuery available in the `<head>` you'd still have to do something like
```javascript
<input data-zdp_pair="javascript: $('#theElemToPairWith')">
```

**Comment by LDemouge** [comment]
> Does it work when setting the `pair` option from JavaScript?

yes, but in my case it isnt a suitable solution as i have a list of date ranges, i need to identify them by id

**Comment by stefangabos** [comment]
Looks like this has been fixed at some point as using a selector like
`<input data-zdp_pair="#theElemToPairWith">`
now works as expected
