### ISSUE TITLE
Cant set enabled hours

### ISSUE THREAD

**Issue by supercain** [stefangabos/Zebra_Datepicker#148]
Hi,

I want to configure the script to enable only a set of available hours like this:

`enabled_hours: ['11', '12', '13', '14', '15', '16', '17', '18', '19']`

but on the picker only 11 is shown and if I try to change it with the arrows then UNDEFINED appears. Enabled minutes wont work either

`enabled_minutes: ['00'],`

is this a bug or im doing something wrong?

Thank you.

**Comment by stefangabos** [comment]
I'll look into it this week. Thank you!

**Comment by stefangabos** [comment]
This is now fixed. It was because I expected those values to be given as integers
```js
enabled_hours: [11, 12, 13, 14, 15, 16, 17, 18, 19]
```
instead of strings
```js
enabled_hours: ['11', '12', '13', '14', '15', '16', '17', '18', '19']
```
Thank you for reporting and sorry it took so long to finally making time for this
