### ISSUE TITLE
How to edit year in calendar 

### ISSUE THREAD

**Issue by maireina** [stefangabos/Zebra_Datepicker#150]
Hi. Date picker can edit year for show to select ?
Ex.1
    2009-2020
******************
2009  2010  2011
2012  2013  2014
2015  2016  2017 
2018  2019  2020

change to
    2552-2563
******************
2552  2553  2554
2555  2556  2557
2558  2559  2560
2561  2562  2563

Thank you very much.

**Comment by stefangabos** [comment]
`direction: ['2552-01-01', false]`
