### ISSUE TITLE
Accepting default time not returned to form

### ISSUE THREAD

**Issue by christophermachew** [stefangabos/Zebra_Datepicker#152]
Hi there. 

On using the option to only pick time (H:i) i.e. 
```
 $('#timepicker').Zebra_DatePicker({
     format: 'H:i',
});
```
the tick icon to accept the time is shown by default. However, if you click on the tick, the value is not returned and the input remains blank. 
You need to first change the time value, and then click on the tick before the time value is accepted and displayed

Hope this is an easy fix...

**Comment by stefangabos** [comment]
Should be fixed now. Thank you for reporting!
