### ISSUE TITLE
CSS Deprecation Warnings when using SCSS

### ISSUE THREAD

**Issue by Damo1155** [stefangabos/Zebra_Datepicker#157]
I've recently brought the Zebra Datepicker into a couple of our projects via NPM.

Upon including the appropriate references and running the compiler we get the following warning.

`DEPRECATION WARNING on line 8, column 8 of <PATH TO SASS FILE>:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.`

All our other imports into the SCSS file don't import CSS files directly and instead only reference the SCSS counterpart.  After doing some digging around our actual issue is the library doesn't support SCSS. 

Are there any plans on migrating the CSS to SCSS or at the very least supporting both SCSS and CSS?

**Comment by stefangabos** [comment]
Zebra_Datepicker is built with SCSS but the scss files are not included with the release files. I will do a release later today with the sass files included. 
thanks for the heads-up

**Comment by Damo1155** [comment]
Thanks for the update, I look forward to getting the latest version.

**Comment by stefangabos** [comment]
i published a release (`1.9.15`) which contains the SASS files. have a look and let me know if it works

**Comment by Damo1155** [comment]
Thanks for the update.

I’ve just finished work for the day so I’ll make this my first task tomorrow morning.

**Comment by Damo1155** [comment]
I've pulled in the latest changes and can confirm it fixes our issue.

Thanks for the quick turnaround.
