### ISSUE TITLE
How to get the selected day when changing view? 

### ISSUE THREAD

**Issue by leomat** [stefangabos/Zebra_Datepicker#162]
Hi,

I would like to set up the date picker with classic options: date and hours enabled.
When the user selects a date, I would like to update the hours enabled (different working hours for a store).

I wanted to retrieve the user choice by the "onChange" function, but the view and elements variables don't contain this information. 

Is there a way to do that? If not, would it be easy for you to code ? 

Thanks for you answer. 

And sorry for my English :/

**Comment by stefangabos** [comment]
Have a look at [this](https://github.com/stefangabos/Zebra_Datepicker/issues/153#issuecomment-632774862)

**Comment by leomat** [comment]
Thanks for the quick reply !
