### ISSUE TITLE
Requires python? 

### ISSUE THREAD

**Issue by mikey186** [stefangabos/Zebra_Datepicker#163]
I installed Zebra_datepicker with npm, and tried to start, and it gave me a list of errors

/ Preparing native dependencies: 0 / 1node-pre-gyp ERR! find Python
node-pre-gyp ERR! find Python Python is not set from command line or npm configuration
node-pre-gyp ERR! find Python Python is not set from environment variable PYTHONnode-pre-gyp ERR! find Python checking if "python3" can be used
node-pre-gyp ERR! find Python - "python3" is not in PATH or produced an error
node-pre-gyp ERR! find Python checking if "python" can be used
node-pre-gyp ERR! find Python - "python" is not in PATH or produced an error
node-pre-gyp ERR! find Python checking if "python2" can be used
node-pre-gyp ERR! find Python - "python2" is not in PATH or produced an error
node-pre-gyp ERR! find Python checking if Python is C:\Python37\python.exe
node-pre-gyp ERR! find Python - "C:\Python37\python.exe" could not be run
node-pre-gyp ERR! find Python checking if Python is C:\Python27\python.exe
node-pre-gyp ERR! find Python - "C:\Python27\python.exe" could not be run
node-pre-gyp ERR! find Python checking if the py launcher can be used to find Python
node-pre-gyp ERR! find Python - "py.exe" is not in PATH or produced an error
node-pre-gyp ERR! find Python
node-pre-gyp ERR! find Python **********************************************************
node-pre-gyp ERR! find Python You need to install the latest version of Python.
node-pre-gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
node-pre-gyp ERR! find Python you can try one of the following options:
node-pre-gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
node-pre-gyp ERR! find Python   (accepted by both node-gyp and npm)
node-pre-gyp ERR! find Python - Set the environment variable PYTHON
node-pre-gyp ERR! find Python - Set the npm configuration variable python:
node-pre-gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
node-pre-gyp ERR! find Python For more information consult the documentation at:node-pre-gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
node-pre-gyp ERR! find Python **********************************************************
node-pre-gyp ERR! find Python
× Preparing native dependencies: 0 / 1

An unhandled error has occurred inside Forge:
node-gyp failed to rebuild '[path-to-app]\node_modules\node-sass'.
Error: Could not find any Python installation to use

Error: node-gyp failed to rebuild '[path-to-app]\node_modules\node-sass'.
Error: Could not find any Python installation to use

    at ModuleRebuilder.rebuildNodeGypModule ([path-to-app]\node_modules\electron-rebuild\src\module-rebuilder.ts:231:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitterdmscheduler@1.0.0 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twitterdmscheduler@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

does this REALLY require python? it doesen't show in the documatation.

**Comment by stefangabos** [comment]
this is a jQuery plugin so obviously it doesn't require python; you need to use the files in the `dist` folders, you don't need to do anything with whatever you are doing there. i need the nodejs tools in the development process
