### ISSUE TITLE
Add support for adding classes to Zebra_datepicker instance

### ISSUE THREAD

**Issue by betheymc** [stefangabos/Zebra_Datepicker#165]
The custom_classes option seems to only apply to certain dates within the Zebra_datepicker.

If there could be a way to add a class to the Zebra_datepicker instance, that would be awesome. I need to be able to set the datepicker's z-index so that it will show over everything else no matter what.

**Comment by stefangabos** [comment]
```css
.Zebra_DatePicker { z-index: 9999 }
```
?

**Comment by betheymc** [comment]
@stefangabos You're right, I could set it in CSS, but the code base I'm working on is fairly large, and setting it with CSS may interfere with other elements with z-index properties. 

I should have specified that I needed to change the z-index via JavaScript. As it turns out however, I no longer need to do this, since I think the datepicker will show up correctly anyway, and setting the z-index didn't make a difference with our previous datepicker (jQueryUI).

Thank you for all your work on this plugin, it is very useful!
