### ISSUE TITLE
Zebra_DatePicker instance doesn't add container on .update()

### ISSUE THREAD

**Issue by betheymc** [stefangabos/Zebra_Datepicker#166]
When I try to add a container to a datepicker instance on `.update()`, the datepicker is still not added into the container, but on the `$('body')` element.

Here's basically what I did:

```
var el = $('input#datepicker');
var inst = el.data('Zebra_DatePicker');
$('<div class="zebra-datepicker-div"></div>').insertAfter(el);

// set the position of the container
el.siblings('.zebra-datepicker-div').first().css({'width': '300px', 'height': '300px', 'top': '1217px', 'left': '803.5px'});

// update datepicker to be in container
inst.update({container: $(el).siblings('.zebra-datepicker-div').first()});
```

**Comment by stefangabos** [comment]
that's not something i thought about - i always felt like the container should be known upfront so updating the container does nothing. but fair point i am now looking into it

**Comment by stefangabos** [comment]
should be fixed, please have a look

**Comment by stefangabos** [comment]
have you had the chance to test this?

**Comment by betheymc** [comment]
@stefangabos sorry I haven't got back with you yet, been super busy at work. I found a workaround, so haven't yet had a chance to test. I will plan to do that in the near future and let you know how it goes.

**Comment by stefangabos** [comment]
ok, thanks!

**Comment by betheymc** [comment]
@stefangabos Just tested this, and it works! I think anyone updating the container should be sure to position the datepicker correctly so that it will actually go inside the container, but the datepicker html definitely shows up inside the container now. Thank you!
