### ISSUE TITLE
How to set a start and end time in the timepicker

### ISSUE THREAD

**Issue by betheymc** [stefangabos/Zebra_Datepicker#167]
Hi,
I am using the timepicker to replace the jQueryUI timepicker. However, I can't seem to be able to set a start time in which all times before it in the day are disabled. I wonder if you have a way to do that, and if not, could that be something added? I think it would be very useful to a lot of plugin users.

Thank you in advance!

**Comment by stefangabos** [comment]
Have a look at [this](https://github.com/stefangabos/Zebra_Datepicker/issues/153#issuecomment-632774862) - this should get you on the right track

**Comment by betheymc** [comment]
Okay thank you. This should help - does this code work when it is only the timepicker, and it is set in 12 hr format?
Also it would be great if I could get the minutes work this way as well.

**Comment by stefangabos** [comment]
the code is generic, you'll have to adapt it to suit your needs

**Comment by betheymc** [comment]
@stefangabos Is there a way to add an option to the plugin called something like "enabled_am_pm"? 
It would only apply if the time format is set to include the am/pm option, and would give the user the ability to enable/disable am and/or pm.
That way, if someone is trying to set start and end times in 12 hr format, they can use a combination of enabled_am_pm option and the code you suggested [here](https://github.com/stefangabos/Zebra_Datepicker/issues/153#issuecomment-632774862) to successfully do it. 

Let me know if that's something you can add.

Thank you!

~Beth

**Comment by stefangabos** [comment]
Setting a date format to one that has AM/PM will enable those (that means using `a` or `A` in the format; see [docs](https://www.php.net/manual/en/datetime.format.php) for the possible format arguments)

**Comment by betheymc** [comment]
@stefangabos Thank you. I do have it set that way. Maybe I wasn't making much sense when I tried to explain that. I need a way to disable PM or AM **only**, like when you set enabled_hours to only certain hours, or enabled_minutes to only certain minutes.

My goal is to have two input timepickers (for start and end times), and write code so that, for example, if the user selects 2:30 PM in the **first** input, then the **second** input would automatically update so that all hours before "2" are disabled (using enabled_hours), and all minutes before "30" are disabled (using enabled_minutes). However, in 12 hr. time format, there is no enabled_ampm option, and in order to make this work, I need to disable the "AM" option only, in this case.

Does that make more sense? Let me know if I can clarify more.
