### ISSUE TITLE
Adding a class to td's in datepicker

### ISSUE THREAD

**Issue by betheymc** [stefangabos/Zebra_Datepicker#168]
I need to be able to add a class to the datepicker td's for styling purposes. I'm not seeing anything about this in the docs - is that something that can be added easily?

**Comment by stefangabos** [comment]
You cannot add a class to the `td`s but you can add one to the date picker, and then target the `td`s from there. see the docs, look for `custom_classes`

**Comment by betheymc** [comment]
@stefangabos thank you! This should work.
