### ISSUE TITLE
Infinite loop when no enabled dates in current year

### ISSUE THREAD

**Issue by b4tch** [stefangabos/Zebra_Datepicker#171]
We found an issue whereby is_disabled was always returning true, resulting in an infinite loop and hanging our site.  It is only caused when there are no enabled dates left in the current year, and the only enabled days are in January of the next month _before_ the current day number (so in our case, only December 31st was affected).

We are using v1.9.0 and the resolution was to add the following code after line 772 (after "`first_selectable_month = 11;`"):

`first_selectable_day = new Date(first_selectable_year, first_selectable_month + 1, 0).getDate();`

and also this code after line 781 ("`first_selectable_month = 0;`"):

`first_selectable_day = 1;`

I believe the latest version (v1.9.17) is still affected but that's minified so I can't tell you how to change that, sorry.

Hope that helps someone out.

**Comment by stefangabos** [comment]
can you please post how the `disabled_dates` is built?

**Comment by stefangabos** [comment]
I used 
`disabled_dates: ['31 12 2020']`
and it didn't break, but maybe I can reproduce it with your setup

**Comment by b4tch** [comment]
Sorry, I meant to state that in my original post.  I am disabling all dates by default (`[* * *]`)

**Comment by stefangabos** [comment]
ok, then what are you using for `enabled_dates` :)
i need to be able to reproduce it

**Comment by stefangabos** [comment]
just post the values you are using to create the date picker

**Comment by b4tch** [comment]
var enabledDates = ["31 12 2020 1-5","2 1 2021 1-5","3 1 2021 1-5","4 1 2021 1-5","5 1 2021 1-5","6 1 2021 1-5","7 1 2021 1-5"];

$('#calendar_collectiondate').Zebra_DatePicker({
		always_visible: $('.the_calendar'),
		disabled_dates: ['* * *'],
		enabled_dates: enabledDates,
		direction: true,
		first_day_of_week: 0,
		format: 'Ymd',
		select_other_months: true,
		onSelect: function(a,b,dateObj,d){
			dateSelected(dateObj);
		}
	});

**Comment by stefangabos** [comment]
ok, i was able to reproduce it by removing `31 12 2020`
awesome, working on it, thank you!

**Comment by b4tch** [comment]
Ahh yes, sorry - that date gets removed through some other code and I neglected to remove it from the example.

Great plugin by the way, thank you for it :)

**Comment by stefangabos** [comment]
Should be fixed now. Do you want me to do a new release so you can grab it via npm?
Are you able to use the latest version or you must stick to 1.9.0?

**Comment by b4tch** [comment]
Our current fix is adequate for now, assuming what I suggested in the original post is satisfactory.  We could probably upgrade to the latest version but it would require some testing which I won't be doing on New Years Eve haha. Thanks for the speedy fix!

**Comment by stefangabos** [comment]
i haven't looked at the solution you provided until now, but that is exactly what the solution was (only also needed at a different place). thanks a lot for the feedback and a happy new year!
