### ISSUE TITLE
Datepicker direction not working for format 'd M Y'

### ISSUE THREAD

**Issue by atiq25101990** [stefangabos/Zebra_Datepicker#173]
Hi Stefan,

I tried using the date picker and it fails in the following scenario when format is 'd M Y':
Future Date Only: ["6 May 2021", "6 May 2022"]
Past Date Only: ["6 May 2020", "6 May 2021"]
Date in Range: ["29 Apr 2011", "14 May 2031"]

Please check and provide any quick fix to a plugin.
![Date does not work](https://user-images.githubusercontent.com/28568601/117252757-c0015f00-ae89-11eb-84c2-ad9f4070cacd.png)

Thanks and regards,
Atiq.

**Comment by stefangabos** [comment]
That's because `6 May 2021` is valid only if the format is `j M Y` 
`d` expects leading 0

**Comment by stefangabos** [comment]
I pushed an update where now things will work with and without leading zeroes for all formats mentioning it, like `d`, `j`, `m, and `n`. not a release yet but out there for testing

**Comment by atiq25101990** [comment]
Thank you so much Stefan. Much appreciated.
