### ISSUE TITLE
Datepicker error in bootstrap nav-tabs 

### ISSUE THREAD

**Issue by Sisytec** [stefangabos/Zebra_Datepicker#177]
Hello :)

I'm having trouble using DatePicker within Bootstrap tabs

[https://jsfiddle.net/Sisytec/hb5mcqfs/2/](https://jsfiddle.net/Sisytec/hb5mcqfs/2/)

Bootstrap tabs 4.5
https://getbootstrap.com/docs/4.6/components/navs/#javascript-behavior

Thanks in advance,
Emilio C.S.

**Comment by stefangabos** [comment]
it looks fine to me. what is the error?

**Comment by Sisytec** [comment]
Hello Stefan, thanks a lot for your reply! 

Please, switch between tabs and you will see an error for the  icon calendar: [https://gyazo.com/16641f6e1e46e67a6fa5891e01eaee7c](https://gyazo.com/16641f6e1e46e67a6fa5891e01eaee7c)

Regards,
Emilio C.S.

**Comment by stefangabos** [comment]
Here's the answer at https://jsfiddle.net/2cpL5vh9/ (it's a function at the bottom)

Basically, when moving to a new tab, we destroy those datepickers and re-create them. 

> In this example I am recreating all  of the datepickers, but you should only work on the ones that are affected - `e.target` in my function gives you the clicked tab and you can work from there. also, you should add a class to the datepickers, something like `datepicker` and then you'd only do `$('.datepicker').Zebra_DatePicker({options})` instead of all those ids

**Comment by Sisytec** [comment]
It works like a charm. Thanks a lot for your help Stefan, and congratulations for your work. 

Have a nice day! Regards,
Emilio C.S.

**Comment by stefangabos** [comment]
I am glad it worked out!
