### ISSUE TITLE
Fix jQuery 3+ warnings

### ISSUE THREAD

**Issue by stefankiv** [stefangabos/Zebra_Datepicker#178]
When using datepicker with jQuery 3+, jquery-migrate prints several warnings about deprecations in the code:
- JQMIGRATE: jQuery.fn.removeAttr no longer sets boolean properties: readonly ([src](https://github.com/stefangabos/Zebra_Datepicker/blob/master/src/zebra_datepicker.src.js#L564))
Possible solution: replace `$element.removeAttr('readonly');` with `$element.prop('readonly', false);` ([src](https://github.com/jquery/jquery-migrate/blob/main/warnings.md#jqmigrate-jqueryfnremoveattr-no-longer-sets-boolean-properties))
- JQMIGRATE: jQuery.isArray is deprecated; use Array.isArray (29 occurrences, [like this](https://github.com/stefangabos/Zebra_Datepicker/blob/master/src/zebra_datepicker.src.js#L633))
Possible solution: replace all `$.isArray` with `Array.isArray` ([src](https://github.com/jquery/jquery-migrate/blob/main/warnings.md#jqmigrate-jqueryisarray-is-deprecated-use-arrayisarray))
- JQMIGRATE: jQuery.trim is deprecated; use String.prototype.trim (5 occurrences, [like](https://github.com/stefangabos/Zebra_Datepicker/blob/master/src/zebra_datepicker.src.js#L1851))
Possible solution: replace all `$.trim` with `text.trim()` or `String.prototype.trim.call( text == null ? '' : text )` ([src](https://github.com/jquery/jquery-migrate/blob/main/warnings.md#jqmigrate-jquerytrim-is-deprecated-use-stringprototypetrim))
- JQMIGRATE: jQuery.fn.mousedown() event shorthand is deprecated ([src](https://github.com/stefangabos/Zebra_Datepicker/blob/master/src/zebra_datepicker.src.js#L2123))
Possible solution: replace `el.mousedown(function() {...})` with `el.on('mousedown', function() {...})` ([src](https://github.com/jquery/jquery-migrate/blob/main/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated))

Thanks in advance!

**Comment by stefangabos** [comment]
This library is compatible with IE 6 :)
Therefore, the only thing that I could change is the `mousedown` related issue
I was thinking about letting IE6 go but I don't think I am ready yet :)

**Comment by stefankiv** [comment]
Ahh.. Sometimes you just have to let it go, you know 😅 

Nevertheless, somehow I missed that, thank you for quick reply!

**Comment by stefangabos** [comment]
I thought more about it and I will make a release next week from which I will be removing the IE6 related things

**Comment by stefankiv** [comment]
That sounds even better!

**Comment by stefangabos** [comment]
better later than never! :)
[stefankiv](https://github.com/stefankiv) thanks for your input on this!
