### ISSUE TITLE
Chrome/Safari on iPhone auto selects today date firing JS events without user input 

### ISSUE THREAD

**Issue by riccardowm** [stefangabos/Zebra_Datepicker#180]
Touching the Zebra Datepicker input field automatically selects today date firing JS events that should only start when the user actually selects a date. Is there any way to fix/prevent this behaviour ?

**Comment by stefangabos** [comment]
i can't confirm this. i am trying it on an iphone 12. please give me more details

**Comment by stefangabos** [comment]
i am using the [examples page](https://stefangabos.github.io/Zebra_Datepicker/) for testing
