### ISSUE TITLE
Allow customization of button text in icon

### ISSUE THREAD

**Issue by atesca09** [stefangabos/Zebra_Datepicker#182]
For localization purposes I need to be able to customize the text of the button in the Zebra_DatePicker_Icon.

https://github.com/stefangabos/Zebra_Datepicker/blame/72ac8a09105909deed9d68dda9d6172eedbeb6e0/src/zebra_datepicker.src.js#L1220

The names of the days and months can already be overwritten.

**Comment by stefangabos** [comment]
hah! how come nobody ever noticed that!

**Comment by stefangabos** [comment]
...but isn't that like never visible?

**Comment by atesca09** [comment]
With the default stylesheet it is pulled out to the left. But because of the line-height not being 16px I want to use my own icon-font and ::before { content: ... } so I ended up with something like this
![image](https://user-images.githubusercontent.com/15890758/132987328-c14269cc-c7a7-4d8f-9f27-defbdff33947.png)

**Comment by stefangabos** [comment]
so you don't want the icon, but only text?

**Comment by stefangabos** [comment]
are you sure you are including the CSS correctly? you should always see the icon and never the text. or, you could use something like `font-size: 0`

**Comment by atesca09** [comment]
Yeah I can hide the text with `font-size: 0;`, but I'd like to use the text and set it with an property on init.

![image](https://user-images.githubusercontent.com/15890758/132993472-f9b9723a-23ba-47d4-94af-cfdea30ca36f.png)

**Comment by stefangabos** [comment]
but why aren't you using the library's CSS because it already has `text-indent: -9000px`
don't get me wrong, i can update the library and change that text, I just want to understand the scenario you are in, and why would you go that way?
so, the CSS for the icon is this
```css
    background: url('icons.png') no-repeat center top;
    border: none;
    cursor: pointer;
    display: block;
    height: 16px;
    line-height: 0;
    padding: 0;
    position: absolute;
    text-indent: -9000px;
    width: 16px;
```
changing just 
```css
background: url('icons.png') no-repeat center top;
```
to point to you pen icon would fix the things

**Comment by atesca09** [comment]
I'm not using `text-indent` because I was planning on using the button text. But I can only use the text, if I'm able to set the text on init. I guess I can work around that.

**Comment by stefangabos** [comment]
no, it's cool, i will add that option

**Comment by stefangabos** [comment]
I pushed a fix. Look in the docs for the `show_icon` property
