### ISSUE TITLE
visualization/layout problem inside hidden divs

### ISSUE THREAD

**Issue by fiscio** [stefangabos/Zebra_Datepicker#183]
Hi, 

I'm using this widget and I really like it!. But there is something that I could not make to work so far. 

This control works flawlessly inside regular divs but fails anytime I want to place it inside a hidden element. 

Since I use Bootstrap and I want to place it in a modal and/or a tab pane.. but it does not work well.. I mean it works but it won't visualize as it should, The size of the element is zero (just a small inputbox) and its icon is misplaced out of it.

I triedto "force" its width via jquery $("#control").css(....)  but with no good results at all,

So, is there any way to make it work properly or a good workaround?

Thank you in advance!

**Comment by stefangabos** [comment]
You'll have to call the `update` method once the container becomes visible (or initialize the date picker when the container becomes visible)
See [here](https://getbootstrap.com/docs/4.0/components/modal/) for the event triggered when the modal becomes visible

**Comment by fiscio** [comment]
Thank you!  I finally decided to initialize it when the modal becomes visible and it worked like a charm!. 

I certainly hadn't realized that!

Keep up the great work
