### ISSUE TITLE
Unable to retrieve the correct date

### ISSUE THREAD

**Issue by kanachrisi** [stefangabos/Zebra_Datepicker#184]
Hi,
I just started using this plugin in my production app, however i am having difficulties to select the date.
Here is how i am retrieving what date the user have selected
`$('#datepicker-start').Zebra_DatePicker({
	direction: false,
	pair: $('#datepicker-end'),
	onChange: function (view, elements) {
            if (view === "days") {
                elements.each(function () {
			$(this).click(function () {
                          startDate = new Date($(this).data('date'));
                          console.log(startDate.toLocaleDateString('en-US')); //returns '1/10/2022' instead of '1/11/2022'
                       });
                });
            }
          }
 });`

**Comment by stefangabos** [comment]
why aren't you using the purpose-built `onSelect` ?

**Comment by stefangabos** [comment]
was your issue solved when using onSelect?
