### ISSUE TITLE
Only allow current month selection

### ISSUE THREAD

**Issue by baffourt** [stefangabos/Zebra_Datepicker#188]
I don't seem to understand the direction property properly, I want the direction to ONLY allow dates in the current month.
When I hardcode the direction with 
`direction: ['01-Nov-2022', '30-Nov-2022']` it works but when these same values are coming from variables, then it doesn't work
```
var today = new Date();
var year = today.getFullYear();
const month = today.toLocaleString('default', { month: 'short' });
var begDate = "'01" + '-' + month + '-' + year + "'";
var lastDayOfMonth = new Date(year, today.getMonth() + 1, 0);
var lastDay = "'" + lastDayOfMonth.getDate() + '-' + month + '-' + year + "'";
console.log("direction: [" + begDate +',' + lastDay+ "]")
$('.datepicker').Zebra_DatePicker({
                direction: [begDate, lastDay],
                format: 'd-M-Y'
});
```
the direction has to be dynamic for every month so it cannot be hard coded. How should this be approached?

**Comment by stefangabos** [comment]
You need to first disable all dates with 
```js
disabled_dates = ['* * * 0,6']
```
and then
```js
enable_dates = ['* 11 2022 *']
```
i haven't tested the above but that should be it

**Comment by stefangabos** [comment]
disregard my previous comment because i just read your comment better this time :)

that is because your code generates this 

`['01-Nov-2022','30-Nov-2022']`

whereas you need

`['01-11-2022','30-11-2022']`

notice the `Nov` instead of `11`

**Comment by baffourt** [comment]
@stefangabos , my date format is `d-M-Y`
Your suggestion does not work even if I hard code it to
```
direction: ['01-11-2022', '30-11-2022']
```
If I however hardcode this
```
direction: ['01-Nov-2022', '30-Nov-2022']
```
My question is, since I cannot hard code the direction for every month, I generate it with some js as above, 
however, the generated code direction with the variables does not work, although the output is the same as the hardcoded value.

**Comment by stefangabos** [comment]
it will not work *only* if the value in variables it's different than the ones you put by hand. i can't see why else wouldn't work...

**Comment by stefangabos** [comment]
you were using extra quotes for some reason
changing this

```js
var begDate = "'01" + '-' + month + '-' + year + "'";
```
to this
```js
var begDate = '01' + '-' + month + '-' + year;
```

and this

```js
var lastDay = "'" + lastDayOfMonth.getDate() + '-' + month + '-' + year + "'";
```
to this
```js
lastDay = lastDayOfMonth.getDate() + '-' + month + '-' + year
```
 
fixes your issue

**Comment by stefangabos** [comment]
here's a [jsfiddle](https://jsfiddle.net/zqtg9v47/)

**Comment by baffourt** [comment]
I have checked the js fiddle, it allows selections from other months aside the current month
