### ISSUE TITLE
Support fluid / responsive layouts (avoid hardcoded widths and heights)

### ISSUE THREAD

**Issue by kwando** [stefangabos/Zebra_Datepicker#19]
I really do like this plugin, and it works like a charm! I use it do display a inline calendar with the `always_visible` option.

The hardcoded heights and widths combined with a responsive layout does not work that great when resizing a browser window though =/ I have to refresh the browser for it to recalculate the widths/heights. I know there is a update method, but I do not wanna resort to window.resize or use some black magic to watch mediaqueries.

**Comment by jeffisowens** [comment]
I'm running into this same issue. I would love to be able to set the width of the calendar to a percentage or even to just have an option to let it fill its container.

**Comment by tanloverluke** [comment]
have you tried making the width a percentage? I have a fixed width of 200px and it works great.

**Comment by jeffisowens** [comment]
You mean within the js code? Because if I set it via CSS, the js overrides
it.

**Comment by imranzahid01** [comment]
Just my 2 cents
I am using Bootstrap4 and if my date-field is hidden then I am having the above issue. What I did was after initialization I remove the calculated width like:

```javascript
$('.datepicker').Zebra_DatePicker({
  format: 'M d, Y',
  show_week_number: 'Wk'
});
$('.Zebra_DatePicker_Icon_Wrapper').each(function() {
  $(this).css('width', '');
});
```

**Comment by ppazos** [comment]
Just found this issue, I have a container div that is hidden by default then it's shown and contains some pickers, the pickers container span has `width: 0px` on it making it's width and the calendar icon to be broken.

![Screenshot 2023-03-16 at 00-01-22 Atomik](https://user-images.githubusercontent.com/1278556/225500285-76275d57-3b35-4df4-99e8-9639f46202ae.png)

With @imranzahid01 solution:

![Screenshot 2023-03-16 at 00-02-30 Atomik](https://user-images.githubusercontent.com/1278556/225500656-95bd88f5-3c30-4547-8745-1a078901fd67.png)

**Comment by stefangabos** [comment]
the fix from @imranzahid01 made its way into the plugin's code - thank you!
