### ISSUE TITLE
Android Pixel 6/7 Firefox "Partial date formats" usability problem

### ISSUE THREAD

**Issue by mccabeservant** [stefangabos/Zebra_Datepicker#192]
**WHAT ACTUALLY HAPPENS**

1. In Firefox on an Android Pixel 6 or a Pixel 7, go to: https://stefangabos.github.io/Zebra_Datepicker/
3. Scroll down to Demo 10: Partial date formats
4. Tap in the input field
5. Tap a year
6. The datepicker disappears and no text has been placed into the input field

**WHAT SHOULD HAPPEN**

- The datepicker should not disappear, but it should display the month options instead

**Comment by stefangabos** [comment]
Thanks for reporting this and sorry for taking so long (I forgot about it)

**Comment by mccabeservant** [comment]
Hey @stefangabos, is this fixed? I just went to https://stefangabos.github.io/Zebra_Datepicker/ in an InPrivate browser, scrolled down to 10, etc, and experienced the exact same problem.

Maybe the code is updated, but the sample is not...? Don't want to go through reinstalling/updating the code until I can see it works!

Thanks!

**Comment by stefangabos** [comment]
it is, as per the commit from september 29th.
i just didn't do a release yet and the examples page use the latest stable release which is from may and doesn't contain the fix
i'll do a release tomorrow and everything will be ok on the examples page.

**Comment by stefangabos** [comment]
I published a new release - 2.2.0 - containing the fix. As soon as it propagates the examples page should start using it 
Thanks!

**Comment by mccabeservant** [comment]
Looks great! Thanks!

**Comment by mccabeservant** [comment]
We really appreciate your code, btw! Thank you for writing and maintaining it!
