### ISSUE TITLE
Disabling all dates freezes the browser

### ISSUE THREAD

**Issue by gkcgautam** [stefangabos/Zebra_Datepicker#25]
If I set
```javascript
$input.Zebra_DatePicker({
    disabled_dates: ['* * *']
});
```
without providing value for `enabled_dates`, it freezes the browser.

Tested on Chrome, Firefox and Safari.

**Comment by stefangabos** [comment]
That is correct and expected behavior. The scripts looks endlessly for the first enabled date so it can show it. I updated the documentation. Thank you!
