### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by OleLaursen** [stefangabos/Zebra_Datepicker#28]
It would be nice with better keyboard handling, for a start perhaps just on focus (tab in) popup the dialog and on blur (tab out) close the dialog. I sometimes have trouble with people not understanding the latter - so they click a date field in a form, realize that they hit the wrong field, press tab and then the popup is still open.

For icing on the cake, it would be nice if you could navigate the dialog through the keyboard, e.g. with the arrow keys.

I had a look at this

http://eternicode.github.io/bootstrap-datepicker/

and if you try out the input field at the bottom, it could be a good source of inspiration.

**Comment by stefangabos** [comment]
It's never too late!
this [commit](https://github.com/stefangabos/Zebra_Datepicker/commit/cb379c3e4dec0e573681240bd603de18e31d67b0) from July 2017 adds a property for opening the date picker on focus and closing when focus is lost.
