### ISSUE TITLE
Not bringing datepicker up on focus

### ISSUE THREAD

**Issue by miprogrammer** [stefangabos/Zebra_Datepicker#32]
Is there no option to bring up the datepicker ONLY on clicking the calendar icon? I don't want to bring it up on focus of the input text, just if the user clicks.

Looking through the documentation doesn't seem there is anything for this, but it seems like a pretty basic request that many people would want to use.

**Comment by stefangabos** [comment]
This is done now, thanks for suggesting!

**Comment by miprogrammer** [comment]
Working perfectly, thanks a bunch!!!
