### ISSUE TITLE
Making a Symfony Bundle of this library ?

### ISSUE THREAD

**Issue by kmelia** [stefangabos/Zebra_Datepicker#36]
Hi,

Do you mind if I make a Symfony Bundle of your Zebra_Datepicker library ?
I have just found your datepicker and it is the most simple, usefull and great jQuery plugin !

A Symfony Bundle will allow a quicker implementation of the library. It could be installed through a composer package.

Let me know what you think about it.

**Comment by stefangabos** [comment]
I don't mind at all, on the contrary! :)

**Comment by kmelia** [comment]
Hi, here is the Symfony Bundle https://bitbucket.org/kmelia/zebra-datepicker-bundle that I did.

It could be installed through the composer package [kmelia/zebra-datepicker-bundle](https://packagist.org/packages/kmelia/zebra-datepicker-bundle). 

The features are simple for the moment, but it works ;)

**Comment by kmelia** [comment]
Th
