### ISSUE TITLE
Triggering a click event on a date option raises error

### ISSUE THREAD

**Issue by wvankuipers** [stefangabos/Zebra_Datepicker#37]
Hi,

I'm using this plugin for one of my projects and it works perfectly.

But now i'm writing some unit tests for the plugin and I found a (possible) problem with the handeling of a click on a date option.

The problem can be reproduced as followed:

Open the datepicker
Simulate a click on a datepicker option:

    $('.Zebra_DatePicker .dp_daypicker tbody tr:eq(3) td:first').click();

The following Exception wil be raised:

    Uncaught TypeError: Cannot read property 'match' of undefined - zebra_datepicker.src.js:1172

That is correct because of this line from the [jQuery specs](http://api.jquery.com/attr/):

    As of jQuery 1.6, the .attr() method returns undefined for attributes that have not been set.

I have created a pull request to fix this issue.

Thank you for the development of this plugin!

Regards,

Wouter

**Comment by kmelia** [comment]
> But now i'm writing some unit tests for the plugin and I found a (possible) problem with the handeling of a click on a date option.

This is great, unit tests are always usefull! But could you provide the unit tests also?

**Comment by wvankuipers** [comment]
Sure, it's based on the Jasmine framework:

        $('<input type="text" id="DateTest" name="DateTest" '
                    + ' class="js-datetime"/>').appendTo('body');

         $el = $('.js-datetime');

         it('Should close on date select', function() {
                var $datePickerPopupHidden;

                $el.Zebra_DatePicker();

                $el.trigger('click');

                $datePickerPopupHidden = $('.Zebra_DatePicker:hidden');

                expect($datePickerPopupHidden.length).toEqual(0);

                $('.Zebra_DatePicker .dp_daypicker tbody tr:eq(3) td:first')
                                                            .click();

                $datePickerPopupHidden = $('.Zebra_DatePicker:hidden');

                expect($datePickerPopupHidden.length).toEqual(1);
        });

**Comment by wvankuipers** [comment]
Hi @kmelia,

I found the cause of the problem, or the cause why it's a problem during my unit tests.
The plugin only adds a empty class atr to each date on hover. Since my test does not simulate a hover the class attr is not added, hence the error.

The implemented fix that I suggested will resolve this issue, but it seems like a edge case problem.

Regards,

Wouter

**Comment by kmelia** [comment]
> it seems like a edge case problem.

OK, it's good to know.
As I am only a user, I let @stefangabos decide if it is an issue.

Have a good day!

**Comment by stefangabos** [comment]
Thanks guys, this is now fixed
