### ISSUE TITLE
Use jQuery UI Position for positioning the Datepicker

### ISSUE THREAD

**Issue by SunboX** [stefangabos/Zebra_Datepicker#41]
Use jQuery UI's Position class for positioning the Datepicker relative to the Textfield. This is more flexible. You could even choose another element to position against.
This also saves a lot (!) of positioning logic in the `zebra_datepicker.js`

Demo: https://jqueryui.com/position/
API Docs: http://api.jqueryui.com/position/

So, the setting:

``` js
$('.datepicker').Zebra_DatePicker({
    default_position: 'above'
});
```

will translate to:

``` js
$('.datepicker').Zebra_DatePicker({
    position: {
        my: "left bottom",
        at: "left top"
    }
});
```

And this setting:

``` js
$('.datepicker').Zebra_DatePicker({
    default_position: 'below'
});
```

will translate to:

``` js
$('.datepicker').Zebra_DatePicker({
    position: {
        my: "left top",
        at: "left bottom"
    }
});
```

**Comment by astonthebrave** [comment]
Is this still supposed to work?  I would like to position the datepicker below the input box but using the following doesn't work.  Have I missed something.

```
$('.datepicker').Zebra_DatePicker({
    position: {
        my: "left top",
        at: "left bottom",
        of: ".datepicker"
    }
});
```
Thanks

**Comment by stefangabos** [comment]
this post was about a suggestion that zebra datepicker to user jQuery UI for positioning
zebra datepicker doesn't use jQuery UI for positioning
as per the docs, you might want to use
```js
$('.datepicker').Zebra_DatePicker({
    default_position: 'below'
});
```

**Comment by astonthebrave** [comment]
Thanks for your reply.  Apologies I misinterpreted the post.

I tried default_position but that moves the datepicker relative to the cursor when what I am looking for is relative to the input.

default_position: 'below' looks like this:

![image](https://github.com/stefangabos/Zebra_Datepicker/assets/38730870/7c8fba9c-df91-4f3c-924b-fb45d762be73)

I would like it to look like the image below which is taken from an old site that used a version of the datepicker from 2012.

![image](https://github.com/stefangabos/Zebra_Datepicker/assets/38730870/4da1baf1-c47d-4b3f-baf9-b80ba0d42e70)

Can that be done.

Thanks

**Comment by stefangabos** [comment]
i just pushed version 2.0.0 of the datepicker. with that you can do this
```js
$('.datepicker').Zebra_DatePicker({
    onOpen: function() {
        var properties = this.data('Zebra_DatePicker'),
            $datepicker = properties.datepicker,
            $parent = $(this),
            parent_position = $parent.offset(),
            parent_height = $parent.outerHeight();
            
        $datepicker.css({
            left: parent_position.left,
            top: parent_position.top + parent_height + 5
        });
    }
});
```

> note that the plugin always tries to keep the datepicker inside the view port so it will auto-arrange it if necessary. with this hack that functionality is suppressed

I will look into adding more default positionings options though

**Comment by astonthebrave** [comment]
Yes, that worked, exactly what I needed.  Thanks for your prompt response.
