### ISSUE TITLE
Latest release (v1.9.1) errors

### ISSUE THREAD

**Issue by DJM75** [stefangabos/Zebra_Datepicker#45]
There's a typo here in the code:

"if (undefined === selected_years) return;"

"selected_years" should actually be "selected_year"

Also, in this release the "view: 'years'" option doesn't work correctly (the first time you click on the datepicker it doesn't show the "years view").

**Comment by jamesinc** [comment]
Can confirm the above issues are true for me also.

**Comment by kacperkrawczyk** [comment]
Same here!

**Comment by stefangabos** [comment]
Fixed. Thanks for reporting!
