### ISSUE TITLE
1.9.2 introduced a new problem

### ISSUE THREAD

**Issue by DJM75** [stefangabos/Zebra_Datepicker#46]
This part of the code where it says "if day is NaN, use an empty string instead" gives a new problem with the datepicker and screws up the layout in the years and month view.

html += '<td' + (class_name !== '' ? ' class="' + $.trim(class_name) + '"' : '') + '>' + ((plugin.settings.zero_pad ? str_pad(day, 2) : day) || '') + '</td>';

(a workaround could be replacing the empty string '' with something like '&ampnbsp;')

**Comment by stefangabos** [comment]
Fixed - &nbsp; should do the trick. Thanks - hopefully this is a final fix :)
