### ISSUE TITLE
Add Public Methods to Clear Selected Date and Set a new Selected Date value

### ISSUE THREAD

**Issue by jasondavis** [stefangabos/Zebra_Datepicker#48]
I would love to see a couple new Public Functions added to the Zebra Date Picker Library.

- **`function clearDate()`**  
- **`function setDate('2015-05-02')`**  

**1)**  **`function clearDate()`** the selected date value, the same way that the button "Clear Date" that is at the bottom of the Date Picker shown in the image below behaves, except it would be a public function that we can called from userland code... 

    // Get Zebra Date Picker Object
    var datePicker = $('#task-modal-due-date-span').data('Zebra_DatePicker');
    
    // Clear the Selected Date
    datePicker.clearDate();
 
![enter image description here][1]

**2)** **`function setDate('2015-05-02')`** which will allow you to simply set the selected Date with Code at anytime without having to initialize the Date Picker plugin and without manually having to call the `update() function` which doesn't always play nice with re-setting a Date.  

Both functions would be able to be called and used like the example below...  

    // Get Zebra Date Picker Object 
    var datePicker = $('#task-modal-due-date-span').data('Zebra_DatePicker');
    
    // Set the Selected Date value to '02/12/2015'
    datePicker.setDate('02/12/2015');

I would be very grateful if anyone contributes such functionality as I don't have the time myself just yet.  I will in the future if nobody else can do it before I get to it though.

  [1]: http://i.stack.imgur.com/QnKzI.png

**Comment by stefangabos** [comment]
This is done now, thanks for suggesting!
