### ISSUE TITLE
position relative to top left or bottom left of input field?

### ISSUE THREAD

**Issue by LukeMcLachlan** [stefangabos/Zebra_Datepicker#52]
I currently have an input field that is set as an 80% width relative to it's container (in my case a table row). How do I then set the offset so that the bottom left of the calendar is aligned to the top left of the input field?

**Comment by grbbabu** [comment]
Hi,

I have similar requirements. Did you implement this?

Thanks,
Ramesh

**Comment by tanloverluke** [comment]
in the end, as per the requirements of my new site, I now have zebra popup in a container that I have placed under the input field. sorry I can't be of any more help.

**Comment by grbbabu** [comment]
Can you share the website that you have implemented this solution?

**Comment by stefangabos** [comment]
You could calculate the difference in width between the container and the parent element, and use that to set the offset property when initializing the datepicker
