### ISSUE TITLE
Starting date jan. 1st, 10000 when no date enabled

### ISSUE THREAD

**Issue by tibo74** [stefangabos/Zebra_Datepicker#53]
When a date range is defined into direction setting, if all the dates within this range are disabled, the search of the first selectable date runs until the year 10000 and show it to the view!
In my case, I used: 
- format: 'm.Y'
- direction: ["04.2015","08.2015"]
- disabled_dates: ["\* 4 2015","\* 5 2015","\* 6 2015","\* 7 2015","\* 8 2015"]

**Comment by tibo74** [comment]
A solution may be to introduce a break in the while loops when looking for a first selectable date when the previous found is disabled. The break will occurs when the last selectable has passed.

**Comment by stefangabos** [comment]
Actually, the behavior is the expected one as you said to the date picker to enable dates between 04.2015 and 08.2015 but then disabled *all* the possible dates between those dates, and sent it in an endless loop searching for the first enabled date. You are right though that it should've stopped when the 08.2015 bound was reached, but I never intended to show the date picker without *any* selectable dates

**Comment by tibo74** [comment]
I aggree with you, and discussed it with my boss. But for our purpose, it could be weird if the datepicker is not shown, even with disabled dates. I will fix it in my fork. Up to you to get the fix or not. :-)
