### ISSUE TITLE
Possible to select any date before January 1, 1000 even using the direction option.

### ISSUE THREAD

**Issue by yu-takahasi** [stefangabos/Zebra_Datepicker#55]
Hello, first of all, thanks for the wonderful plugin!

Now, I'd like to report a bug regarding "direction" option that allows to select a date between 2 specific dates. It's actually possible to select any dates before January 1st 1000 (I mean, "1000-01-01"), even if some range has been specified like this: direction:["2000-01-01", "2020-12-31"]. 

If you want to try and see this problem right now, 
access to the following demo site,
http://stefangabos.ro/jquery/zebra-datepicker/
and do the following operation:

1) Open the Zebra_DatePicker in the section "5. Dates can be selected between 2 specific dates."
2) Change the mode of the DatePicker to the year-picker mode.
3) This is the toughest work, but click "<<" button a lot until you reach years below 1000.
4) Select any date before January 1, 1000.
   -> You can select the date, even if the demo mode specifies the direction between '2012-08-01' and '2012-08-12'.

I'm looking into the original JS source, trying to find the cause of this problem now...
bu if anyone know something, let me know how I can avoid this problem.

Regards,
yu-takahasi

**Comment by yu-takahasi** [comment]
If you want to try and see this problem right now, 
access to the following demo site,
http://stefangabos.ro/jquery/zebra-datepicker/
and do the following operation:

1) Open the Zebra_DatePicker in the section "5. Dates can be selected between 2 specific dates."
2) Change the mode of the DatePicker to the year-picker mode.
3) This is the toughest work, but click "<<" button a lot until you reach years below 1000.
4) Select any date before January 1, 1000.
   -> You can select the date, even if the demo mode specifies the direction between '2012-08-01' and '2012-08-12'.

I'm looking into the original JS source, trying to find the cause of this problem now...
bu if anyone know something, please let me know.

**Comment by stefangabos** [comment]
O
On 25 Aug 2015 05:22, "yu-takahasi" <notifications@github.com> wrote:
>
> If you want to try and see this problem right now,
> access to the following demo site,
> http://stefangabos.ro/jquery/zebra-datepicker/
> and do the following operation:
>
> 1) Open the Zebra_DatePicker in the section "5. Dates can be selected
between 2 specific dates."
> 2) Change the mode of the DatePicker to the year-picker mode.
> 3) This is the toughest work, but click "<<" button a lot until you reach
years below 1000.
> 4) Select any date before January 1, 1000.
> -> You can select the date, even if the demo mode specifies the direction
between '2012-08-01' and '2012-08-12'.
>
> I'm looking into the original JS source, trying to find the cause of this
problem now...

**Comment by stefangabos** [comment]
This is now fixed. Thanks for reporting!
