### ISSUE TITLE
when only month and year selection is enabled then direction property is not working

### ISSUE THREAD

**Issue by amitcw** [stefangabos/Zebra_Datepicker#57]
when only month and year selection is enabled then direction property is not working for disabling month & year.
I want that user can't select future month and year.

Example:
$('#datepicker-example11').Zebra_DatePicker({
        format: 'm Y',
	direction: [false,'2014-01-01']
    });

**Comment by stefangabos** [comment]
As per documentation, the date in the "direction" property has to be in the format specified by the "format" property. Therefore, for your example to work, you have to have "01 2014" instead of "2014-01-01"
