### ISSUE TITLE
How to trigger Zebra Datepicker with click on other element?

### ISSUE THREAD

**Issue by echteinfachtv** [stefangabos/Zebra_Datepicker#6]
First I tried the jquery way, which did not work: 

```
$('#datepickbtn').click(function() {
    $('input#datepicker').trigger('click');
});
```

Then I used the plugin's methods: 

```
$('#datepickbtn').click(function() {
    var datepicker = $('input#datepicker').data('Zebra_DatePicker');
    datepicker.show();
});
```

This seems to work, however, if the user clicks again on the button #datepickbtn the datepicker does not hide again. What is the proper way to check if it is visible, there seems to be no property. 

Thank you.

PS: Implemented here: http://www.echteinfach.tv/ferien/ (click on button "Kalender").

**Comment by JccSanabria** [comment]
Hi Stefan, is there an attribute or method to only show calendar when the user clicks the calendar icon not the input?

**Comment by stefangabos** [comment]
Set `open_icon_only` to `true`

**Comment by JccSanabria** [comment]
thanks! :)
