### ISSUE TITLE
Bower not installing

### ISSUE THREAD

**Issue by mynumbercrunching** [stefangabos/Zebra_Datepicker#60]
new:public me$ bower install zebra-datepicker
bower cached        git://github.com/stefangabos/Zebra_Datepicker.git#1.9.2
bower validate      1.9.2 against git://github.com/stefangabos/Zebra_Datepicker.git#*
bower new           version for git://github.com/stefangabos/Zebra_Datepicker.git#*
bower resolve       git://github.com/stefangabos/Zebra_Datepicker.git#*
bower download      https://github.com/stefangabos/Zebra_Datepicker/archive/1.9.3.tar.gz
bower extract       zebra-datepicker#* archive.tar.gz
bower EMALFORMED    Failed to read /var/folders/w5/ypc2dxbd2psf2z9ggwxpblh40000gp/T/benson/bower/1c7c2a9c4ab0a4a4c06e4ddc815e0fe9-7795-VMN3QT/bower.json

**Comment by stefangabos** [comment]
I know, there's a bug in bower.json but is now fixed it's just that I am doing some more updates before I do another release. Everything will be fine in a few days

**Comment by stefangabos** [comment]
This is now fixed, but note that the name has changed (there's now an underscore instead of a dash in the name) and now you can install it by calling
```
bower install zebra_datepicker
```
