### ISSUE TITLE
Date Picker vanishes in mobile while changing from landscape to portrait mode and vice versa

### ISSUE THREAD

**Issue by grbbabu** [stefangabos/Zebra_Datepicker#61]
Hi,

I would like to use your library in one my project. It satisfies all my requirements. Thanks for building a wonderful date picker library.

While testing it in a mobile device, I came across this issue "Date Picker vanishes in mobile phone while changing from landscape to portrait mode and vice versa".

Thanks,
Ramesh Babu

**Comment by stefangabos** [comment]
That is the intended behavior. In real life situation it is highly unlikely that users will chabne orientation while picking a date
