### ISSUE TITLE
Option to hide all views except days?

### ISSUE THREAD

**Issue by lesliecdubs** [stefangabos/Zebra_Datepicker#66]
Great plugin!

I need to be able to only show the monthly view (so the user is unable to click to view all months in the year, or the option of years). Is there any way to control that?

**Comment by stefangabos** [comment]
Unfortunately, that is not currently possible but it's a very good idea! I'll implement that as soon as I can (one week, maybe).Thanks!

**Comment by lbass2** [comment]
Thanks! I'll keep an eye out for the update.

**Comment by stefangabos** [comment]
...wait, it seems that it's not so clear for me, after all :)
- what is the user selecting - a day of month or just a month? can you please walk me through what you were trying to achieve? thanks!

**Comment by lesliecdub** [comment]
Thanks for following up. 

The calendar would load in month view, and the user could still move the calendar forward or backward, month by month, using the arrows.

The name of the month, however, would not be clickable and the view that shows the year and all months in it would not be visible. I want to use this calendar but there will only be one or two events a month, and likely not scheduled more than one month in advance, so the yearly view is not necessary.

The user could select a day of month as usual.

**Comment by stefangabos** [comment]
This will come as a shock but...I added a new property called `fast_navigation` which, when set to `false`, disables the default behaviour that allows the users to quickly navigate through months and years by clicking on the date picker's top label

I *know* it took two and a half years but thank you and sorry it took so long! Better later than never...I guess :)
