### ISSUE TITLE
Custom classes no longer working

### ISSUE THREAD

**Issue by westphalen** [stefangabos/Zebra_Datepicker#67]
In commit 257973b you changed the condition `custom_classes && custom_classes.length > 0` to `$.isArray(custom_classes)`. However, as per your documentation and code, `custom_classes` will never be an array, it will always be an object. Thus the condition fails and function `get_custom_class` will never return any results.

**Comment by stefangabos** [comment]
This is now fixed in the latest commit. Thanks a lot!
