### ISSUE TITLE
Which files need to be hosted

### ISSUE THREAD

**Issue by pvnr0082t** [stefangabos/Zebra_Datepicker#69]
Hi @stefangabos ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host your project on cdnjs.
Are the files in [public](https://github.com/stefangabos/Zebra_Datepicker/tree/master/public) folder is for distribution usage? if not, could you help us find out the main files?
Thank you.

https://github.com/cdnjs/cdnjs/issues/7443
https://github.com/cdnjs/cdnjs/pull/7797

**Comment by stefangabos** [comment]
Hello,
Yes, the files in "public" are the ones. The same as you would get when installing via npm. See https://www.npmjs.com/package/zebra_datepicker

**Comment by stefangabos** [comment]
...but remember that one of the themes is also required (one stylesheet and associated images, that is)

**Comment by pvnr0082t** [comment]
@stefangabos Thanks for your help. :+1:

**Comment by stefangabos** [comment]
No, guys, thank YOU! :)
