### ISSUE TITLE
You can not instantiate object without putting the current date

### ISSUE THREAD

**Issue by eduardobarbiero** [stefangabos/Zebra_Datepicker#73]
```javascript
$('.datepicker').Zebra_DatePicker({
    direction: [true], // Direcao para ser desabilitado, neste caso [true], nao pode ser selecionada datas anteriores a atual
    format: 'd/m/Y',
    always_visible: $('#agendamentos-date-picker'), // Container onde o componente sera carregado
    disabled_dates: ['* * * 0,1,2,3,4,5,6'], // Desabilita todos os dias da semana
    enabled_dates: dates_availables // Datas que estarao disponiveis para utilizar
  });
```

In this case I'm going through an array of dates that are valid, however if I do not put today's date, it does not load, entering into an infinite loop.

Thanks.

**Comment by stefangabos** [comment]
there's probably something wrong with whatever is in your "dates_available" variable. can you post it?

**Comment by eduardobarbiero** [comment]
It a simple array like this:
```javascript
["16 05 2016", "17 05 2016", "18 05 2016"]
```
However if I remove the current date(" 16 05 2016"), enters looping.

Thanks!

**Comment by stefangabos** [comment]
The problem is the setting of your "direction" property which is invalid as you set it (if you set it as an array,it *has* to have 2 values)
Set it to
```javascript
direction: true
````
and you'll be fine

**Comment by eduardobarbiero** [comment]
Works fine! Thanks @stefangabos.

**Comment by stefangabos** [comment]
You're welcome!
