### ISSUE TITLE
disabling specific dates on when datepicker is open

### ISSUE THREAD

**Issue by JsGuru30** [stefangabos/Zebra_Datepicker#82]
Hello,
What I am trying to accomplish is when I open the datepicker, I want to disable very specific dates that I store in the array. So for example my array is 
` var dateArray = [];
 dateArray.push(weekDate);`
Where weekDate is the date that I need to disable in format like 2017/04/21
I am not finding any examples on how to do this inside of onOpen function of the datepicker.
Thanks!

**Comment by tonprince** [comment]
I am facing the same problem. I want to disable a specific date in the date picker p.e. ['30 06 2017'] but it is not working. Is this feature supported or not? Thanks.

**Comment by stefangabos** [comment]
hmmm, something seems to be broken - i'm looking into it

**Comment by tonprince** [comment]
Dear Stefan
I found the problem already, but not sure if the fix is correct.

The check if rule[3] is equals "*" did not succeed as rule[3] itself is of
type array and not string.

I created a pull request.

Kind regards,

Stef

2017-06-27 1:20 GMT+07:00 Stefan Gabos <notifications@github.com>:

**Comment by stefangabos** [comment]
Merged the pull request and did some more updates. Should work now
