### ISSUE TITLE
Positioning of hidden date input

### ISSUE THREAD

**Issue by wicketr** [stefangabos/Zebra_Datepicker#85]
The positioning is not being calculated correctly or at least not uniformly when showing a hidden input element. Is this fixable, or is there a better way to work around this?

See example here where the first element is created on a regular input, and the second one is created on a hidden input: https://codepen.io/wicketr/pen/JNZVEo

**Comment by stefangabos** [comment]
For now, once you make a previously hidden date picker visible, you'll have to also call the `update` method
So, once you show the div you'll have something like
```js
var dp = $('#datepicker-example2').data('Zebra_DatePicker');
dp.update();
```
