### ISSUE TITLE
TypeError: this.split is not a function

### ISSUE THREAD

**Issue by tonprince** [stefangabos/Zebra_Datepicker#87]
When trying to update the datepicker with disabled dates and a custom class there is an exception thrown:

`node.data('Zebra_DatePicker').update({
    disabled_dates : disabledDates,
    custom_classes : {
      'custom' : [ disabledDates ]
    }
});`

**TypeError: this.split is not a function[Learn More] zebra_datepicker.min.js:1:2189**

**Comment by stefangabos** [comment]
Can you show me a sample of what's in `disabledDates` - I suspect there's the problem as I tried with some random stuff and I didn't get the error

**Comment by stefangabos** [comment]
Oh, wait - you're the guy from the other issue :) - ok, I haven't tried it from inside the onOpen - I'll check now

**Comment by tonprince** [comment]
Hi
Yes it is me again :-)

I call it inside onChange, it is a lazy loading of disabled dates from the
server.



2017-06-28 0:13 GMT+07:00 Stefan Gabos <notifications@github.com>:

**Comment by stefangabos** [comment]
I can't reproduce it. Can you paste your `disableDates` please?

Here's how I use it

```javascript        
onChange: function(view, elements) {
    var dp = $(this).data('Zebra_DatePicker');
    dp.update({
        disabled_dates: ['10-19 07 2016,2017', '21 07 2017'],
        custom_classes: { 'custom': ['10-19 07 2016,2017', '21 07 2017']}
    });
}
```

**Comment by stefangabos** [comment]
...also, make sure you are using the latest commit, not the broken release

**Comment by tonprince** [comment]
I fixed the problem on line 521 in src:

if ($.isArray(dates) && dates.length > 0)


*dates = [].concat.apply([], dates);*
Not sure if that is the best solution, but it works now.

2017-06-28 0:14 GMT+07:00 tonprince@gmail.com <tonprince@gmail.com>:

**Comment by stefangabos** [comment]
your `disabledDates` is an object?

**Comment by tonprince** [comment]
Here the snapshot:

[image: Inline-Bild 1]

2017-06-28 0:23 GMT+07:00 Stefan Gabos <notifications@github.com>:

**Comment by stefangabos** [comment]
didn't work. you can email it to me if it's easier for you

**Comment by tonprince** [comment]
sorry, my fault, the server returned a wrong object in a few cases.

Sorry for the trouble. all fine :-)

2017-06-28 0:29 GMT+07:00 Stefan Gabos <notifications@github.com>:
