### ISSUE TITLE
Does this plugin support i18n.

### ISSUE THREAD

**Issue by bidiu** [stefangabos/Zebra_Datepicker#89]
I really need this feature, so does it support?

**Comment by stefangabos** [comment]
You can use it in your language by setting the following properties when initialising the library
- `days`
- `days_abbr` (optional, depending on your language)
- `first_day_of_week` (optional, depending on your language)
- `lang_clear_date`
- `months` 
- `months_abbr` (optional, depending on your language)
- `show_select_today`

**Comment by bidiu** [comment]
Thanks you so much for reply, I know how to do it. Great plugin btw. I'm closing this issue.
