### ISSUE TITLE
Direction doesn't work properly

### ISSUE THREAD

**Issue by nunoguerra** [stefangabos/Zebra_Datepicker#90]
Maybe it is a bug:

I want a pair of start date and end date. In start date I want the datepicker allow past dates but no future dates and in end date I want the picker allow past dates after start date selected e not allow more future that today.

I'm trying it in this way:

```
$('.start').Zebra_DatePicker({direction:false, pair:$('.end')});
$('.end').Zebra_DatePicker({direction:false, pair:$('.start')});
```

But this doesn't work, start date works nice, but the end date no...

Can you help?

**Comment by stefangabos** [comment]
Remove the `pair` property from the second picker. Only the first needs it

**Comment by nunoguerra** [comment]
Ok, but even without pair, this doesn't  work.

The .end date can't see dates more future than .start date selected and what I want is the .end date can't see dates more future than today.

Example:

if .start date is 2008-05-15, the .end date might be more >2008-05-15 and not >today.

**Comment by stefangabos** [comment]
I just tried it with example #7 by just changing the `direction` property to`false` for both and it works

**Comment by stefangabos** [comment]
Also, after you removed the `pair` property from your code, make sure you are not loading a cached version

**Comment by nunoguerra** [comment]
No, this doesn't work.

Please try to select 2017-06-01 and 2017-07-01, you will can't...

Can try here: http://dev.nunoguerra.com/zebra/

**Comment by stefangabos** [comment]
Ok, had a look and now I understand correctly the problem. unfortunately, for now, this is how it works and it works as per the documentation. I thought it is an easy fix but realised that the behaviour needs to be changed for any kind of `direction` and, depending on the situation, the date selected in the first date picker needs to be the ending date while other times, like in your case, it needs to be starting date. 

I couldn't come up with a satisfactory solution and I need some more time to think about it. 

Until then, here's a solution to your problem

```javascript
var today = new Date;
$('#datepicker-example7-end').Zebra_DatePicker({
    direction: [true, today.getFullYear() + '-' + ((today.getMonth() + 1 < 10 ? '0' : '') + (today.getMonth() + 1)) + '-' + today.getDate()]
});
```

**Comment by nunoguerra** [comment]
Ok no problem, I understand.

Thanks!

**Comment by nunoguerra** [comment]
Well, this works if format is 'YYYY-MM-DD' but doesn't work if the format is 'm Y'.

Some suggestion to put it works on this format 'm Y'?

Thanks!

**Comment by nunoguerra** [comment]
Ok, this works:

`direction:[true, ((today.getMonth() + 1 < 10 ? '0' : '') + (today.getMonth() + 1)) + ' ' + today.getFullYear()]`

Thanks!
