### ISSUE TITLE
Browser freezes on Firefox and Safari for very specific enabled dates

### ISSUE THREAD

**Issue by edison** [stefangabos/Zebra_Datepicker#91]
Hi,

There is something very strange happening when I set the `enabled_dates` config in a very special case. This is an example of configuration that makes Safari and Firefox freezes. This problem never happens in Chrome.

Here is some examples of configs that freezes the browser:

```javascript
// Example 1
enabled_dates: ["15 10 2017"]
```

```javascript
// Example 2
enabled_dates: ["15 10 2017", "29 10 2017"]
```

Apparently, when some date between day 15 and 30 October is enabled, browser freezes.

But, if you enable any date between 1 and 14, browser does not freeze. Even if you use the same enabled dates before. Here is some examples that does not freeze the browser.

```javascript
// Example 1
enabled_dates: ["15 10 2017", "14 10 2017"]
```

```javascript
// Example 2
enabled_dates: ["5 10 2017"]
```

Other months also works properly:

```javascript
// Example 3
enabled_dates: ["15 9 2017"]
```

As you can see, it appears to be specific for the month of October, when you don't have enabled dates before or equal to 14 and after 1.

I tried to figure out the problem, but I couldn't. Maybe some brilliant mind who is familiarized with the project can figure out the problem. 🙏

Thanks,

**Comment by stefangabos** [comment]
ok, i'll look into it over the weekend

**Comment by stefangabos** [comment]
Can you please post your entire set of options you are using?

**Comment by edison** [comment]
Hi,

Here is the config I'm using. Actually Im using the parameter `enabled_dates` through `data-zdp_enabled_dates` HTML5 attribute.

```javascript
date_field.Zebra_DatePicker({
  always_visible: $('#datepicker-container .datepicker'),
    format: 'd/m/Y',
    direction: true,
    disabled_dates: ['* * * *'],
    enabled_dates: ["15 10 2017", "18 10 2017"],
    onSelect: function() {
      if ($('.datepicker-loader').length > 0) {
        $('.datepicker-loader').show();
        $('form.summary').submit();
      }
   }
});
```

**Comment by stefangabos** [comment]
I have Firefox 54.0.1 (32-bit) and it doesn't freeze. As for Safari I only have the old one that's available for Windows (5.1.7). What versions do you have? I'll try with BrowserStack if they have what you're having

**Comment by edison** [comment]
Hi,

Thanks for your attention. I uploaded a clean and "freezing" version of the code I mentioned, as you can see here: https://s3-sa-east-1.amazonaws.com/compradeingressos/extra/datepicker/index.html

This is my Safari version: 10.1.1 (12603.2.4) - Freezing
This is my Firefox version: 54.0.1 (64-bit) - Freezing
This is my Chrome version: 59.0.3071.115 64 bits - NOT Freezing

All of this is on MAC OS X. I already tested on Windows and the same thing occurs: Only worked on Opera and Chrome. But I don't remember the version of the browsers on Windows.

If you open the link I provided in you last version of Firefox, it will probably freeze.

Thanks,

**Comment by edison** [comment]
Here is what my Firefox reported:

```
Error: Script terminated by timeout at:
str_concat@https://s3-sa-east-1.amazonaws.com/compradeingressos/extra/datepicker/zebra_datepicker.min.js:3040:25
```

The problem seems to reside on `str_concat` function, at line 3040 in the lib file I loaded.

**Comment by stefangabos** [comment]
I really sorry but I am unable to reproduce it...
I've tried with BrowserStack and opened the link with Safari 10.1.1 (12603.2.4) and it didn't freeze. I've also installed Firefox 54.0.1 64bit (I previously had the one with 32 bits) but still no freezing.

**Comment by edison** [comment]
This is very strange, the following link continues to freeze here:

https://s3-sa-east-1.amazonaws.com/compradeingressos/extra/datepicker/index.html

When you open this link in the browsers I pointed, are you seeing the calendar input? Because when it freezes the calendar input never appears.
