### ISSUE TITLE
Time return is not working

### ISSUE THREAD

**Issue by rajeshdk** [stefangabos/Zebra_Datepicker#93]
Hi,
I want to report an issue. 
```
 $('#mydate').Zebra_DatePicker({
format: 'Y-m-d H:i'
 });
```
The output is
2017-08-15 H:i
Please suggest any solution.
jQuery JavaScript Library v2.1.4

**Comment by stefangabos** [comment]
I'll look into it later today. Thanks!

**Comment by stefangabos** [comment]
I can't confirm - it seems to be working ok. Make sure you are downloading the latest *commit* and not the release. The current release (1.9.6) doesn't have the time feature

**Comment by rajeshdk** [comment]
Okay Sir, I will test. Thank you.
