### ISSUE TITLE
It would be useful to have a translation file

### ISSUE THREAD

**Issue by bogdandragomir** [stefangabos/Zebra_Datepicker#94]
Hi Stefan,

What do you think about a folder /lang with translation files and a constant in the library to set the current language?

Thank you!
Bogdan

**Comment by stefangabos** [comment]
I am not sure about this since it's pretty easy set up the date picker in another language...
Nevertheless, I will consider this option. Thanks!

**Comment by yark** [comment]
It's easy, but it need too be done at every page where you using datepicker.
