### ISSUE TITLE
 IE 8 compatibility issues

### ISSUE THREAD

**Issue by seven7ma** [stefangabos/Zebra_Datepicker#95]
At first ,This tool is very nice.
But I cant use it in IE8 browrer.
How to set Zebra_Datepicker  to use in IE 8 ? 
Could you please give the solution to the problem?
I'll be thank you so much.

**Comment by stefangabos** [comment]
Can you please give me more information, please? What actually happens?

**Comment by seven7ma** [comment]
I use the zebra in my project, it has no problem running in other browrer, 
But click on the Ie8 can not pop up the time option.
This is my code :
	$('#start').Zebra_DatePicker({
				direction: false,
				show_week_number: true,
				show_other_months: true,
				pair: $('#end')
			});

How can i set it to surport IE8?

**Comment by stefangabos** [comment]
There's no time option for the config you sent me. Also, the time option is now available in the latest release but only if you download the latest commit. You also have to set the `format` property to a value that contains time. Nevertheless I'll try and test it in IE8

**Comment by seven7ma** [comment]
Thank you for your reply,I'll check the new commit,Will your next step be posted in your blog?

**Comment by seven7ma** [comment]
By the way,you look really like Robert De Niro.
