### ISSUE TITLE
onChange event not working

### ISSUE THREAD

**Issue by donpro2** [stefangabos/Zebra_Datepicker#97]
I have an Input field with id=preplanDate. I want to trigger an event when the date is changed.  My code for binding the Zebra Datepicker to the Input field is below. What is happening is that the event is triggered when I click into the field or click the icon. Nothing happens when I change it. It looks like the onChange is bound to onSelect. I am using version 1.9.6. Is there a fix for this?

$('#preplanDate').Zebra_DatePicker({
    format: 'M-d-y',
    onChange: function() { 
        alert('changed');
    }
});

**Comment by stefangabos** [comment]
Seems to be working. Make sure you are not confusing the [onChange](https://github.com/stefangabos/Zebra_Datepicker#onchange) event with the [onSelect](https://github.com/stefangabos/Zebra_Datepicker#onselect) event. The first one fires whenever the "view" is changed while the other one is fired when a date is selected.
