### ISSUE TITLE
Bower install problem

### ISSUE THREAD

**Issue by tbba** [stefangabos/Zebra_Datepicker#98]
Bower seems to install not the latest version, the timepicker is broken there.
Downloading the project and uploading it to the website makes everything work.
Maybe the unchanged version number is the problem?

**Comment by stefangabos** [comment]
The version with the timepicker is currently in "beta". It will be available on Bower once all the issues are sorted out

**Comment by tbba** [comment]
I see, thank you. 

I did not realize it's that brand new. I was just following the manual from GitHib and it there was no effect with the Bower-synched local version.

Your new timepicker is becoming such a cool feature that this was the reason to switch the datepicker from UIKIT to your one. Thank you very much for your time end efforts. Time to say goodbye also to the jQueryUI timepicker.
