### ISSUE TITLE
direction: false and time 

### ISSUE THREAD

**Issue by tbba** [stefangabos/Zebra_Datepicker#99]
I have set
direction: false,
I cannot select a date newer than today (great)
but I can select a time today newer than now (ups?)

I think it would be cool if the time was also adhering to the direction setting.

**Comment by stefangabos** [comment]
good catch! i'm looking into it now

**Comment by stefangabos** [comment]
...but realising that it probably wouldn't make much sense fixing it as users will not understand why they aren't able to select certain times. and i don't want to show messages...any ideas on a solution for this?

**Comment by tbba** [comment]
Valid point. Actually I habe not seen a timepicker yet in the wild with a restriction, i must admit.

For my website the correct time setting is very important.
My solution I try now is to show an error message 'onClose' if the selected time is in the future.
